export const CONFIG = {
  tickMinutes: 30,
  speeds: { 0: 0, 1: 30000, 2: 15000, 4: 7500, 6: 5000, 10: 3000 },
  maxLogs: 60,
  fireMaxWood: 5,
  fatigueRestThreshold: 90,
  restDurationHours: 4,
  difficulties: {
    easy: { label: 'Lätt', workMultiplier: 1.3, negativeEventMultiplier: 0.7, positiveEventMultiplier: 1.1 },
    normal: { label: 'Normal', workMultiplier: 1.0, negativeEventMultiplier: 1.0, positiveEventMultiplier: 1.0 },
    hard: { label: 'Hård', workMultiplier: 0.8, negativeEventMultiplier: 1.4, positiveEventMultiplier: 0.9 }
  },
  stateProfiles: {
    work: { rationNeedPerHour: 0.22, waterNeedPerHour: 0.22, hungerPerHour: 6, thirstPerHour: 8, moralePerHour: -0.4, healthPerHour: 0, fatiguePerHour: 12, outputMultiplier: 1, discoveryChance: 0.03 },
    philosophize: { rationNeedPerHour: 0.06, waterNeedPerHour: 0.08, hungerPerHour: 3, thirstPerHour: 4, moralePerHour: 1.5, healthPerHour: 1.0, fatiguePerHour: -6, outputMultiplier: 0, discoveryChance: 0.10 },
    rest: { rationNeedPerHour: 0.02, waterNeedPerHour: 0.03, hungerPerHour: 2.4, thirstPerHour: 3.5, moralePerHour: 0, healthPerHour: 0, fatiguePerHour: 0, outputMultiplier: 0, discoveryChance: 0 },
    care: { rationNeedPerHour: 0.12, waterNeedPerHour: 0.12, hungerPerHour: 4, thirstPerHour: 6, moralePerHour: 0.2, healthPerHour: 0, fatiguePerHour: 5, outputMultiplier: 0, discoveryChance: 0.01 },
    patient: { rationNeedPerHour: 0.03, waterNeedPerHour: 0.05, hungerPerHour: 2.4, thirstPerHour: 3.5, moralePerHour: 0.4, healthPerHour: 0, fatiguePerHour: -4, outputMultiplier: 0, discoveryChance: 0 },
    away: { rationNeedPerHour: 0, waterNeedPerHour: 0, hungerPerHour: 3.5, thirstPerHour: 4.5, moralePerHour: 0.5, healthPerHour: 0, fatiguePerHour: -4, outputMultiplier: 0, discoveryChance: 0 }
  },
  rates: {
    fireConsumptionPerHourPerLevel: 0.10,
    starvationHealthLossPerHour: 2.8,
    dehydrationHealthLossPerHour: 3.2,
    severeNeedRecoveryBlockThreshold: 70,
    hungryMoraleLossPerHour: 1.2,
    thirstyMoraleLossPerHour: 1.2,
    awakeFoodMaxPerHour: 0.5,
    awakeWaterMaxPerHour: 0.65,
    foodHungerReductionPerUnit: 65,
    waterThirstReductionPerUnit: 80,
    eatWhenHungerAbove: 20,
    drinkWhenThirstAbove: 20,
    eatUntilHunger: 5,
    drinkUntilThirst: 5,
    coldNightHealthLossPerHourNoFire: 2,
    coldNightMoraleLossPerHourNoFire: 2,
    restFatigueRecoveryPerHourByFireLevel: { 0: 8, 1: 12, 2: 18, 3: 24, 4: 30 },
    restHealthRecoveryPerHourByFireLevel: { 0: 0.5, 1: 1, 2: 2, 3: 3.5, 4: 5 },
    restMoralePerHourByFireLevel: { 0: -2, 1: -0.5, 2: 0.3, 3: 0.8, 4: 1.3 },
    careHealPerHour: 6,
    careMoralePerHour: 1,
    woodPerHour: 0.8,
    foodPerHour: 0.8,
    waterPerHour: 0.8,
    tenderWoodPerHour: 0.35,
    tinderWoodCostPerHour: 0.35,
    feedFireWoodPerHour: 0.9,
    clayPerHour: 0.9,
    bambooPerHour: 0.8,
    timberPerHour: 0.28,
    stonePerHour: 0.5,
    fiberPerHour: 0.6,
    fishFoodPerHour: 2.4,
    huntFoodPerHour: 0.35,
    huntLeatherPerHour: 0.18
  },
  shelterBalance: {
    capacityPerHut: 4,
    restHealthBonusPerCoverage: 1.2,
    restFatigueBonusPerCoverage: 4,
    restMoraleBonusPerCoverage: 0.8,
    passiveMoraleBonusPerCoverage: 4
  },
  council: {
    exploration: {
      minSurvivors: 5,
      requiredDiscoveries: ['pots', 'backpack', 'fire_building', 'spear'],
      image: 'resources/ui/council.png',
      title: 'Öråd',
      subtitle: 'Expeditioner kan planeras',
      text: 'Gruppen samlas runt elden. Krukor kan bära vatten, ryggsäckar kan bära utrustning, tändved kan ge eld på vägen och spjut kan hålla faror borta. Det är dags att sluta bara överleva i lägret och börja utforska ön.',
      buttonText: 'Öppna fas 2'
    },
    raft: {
      image: 'resources/ui/council.png',
      title: 'Öråd',
      subtitle: 'Flotten måste byggas',
      text: 'Nu har gruppen karta och kompass. Nästa steg är att planera en flotte stor nog för alla, med segel, rigg, skydd och proviant för en lång resa.',
      buttonText: 'Öppna fas 3'
    },
    departure: {
      image: 'resources/ui/council.png',
      title: 'Öråd',
      subtitle: 'Det är dags att fatta beslut',
      text: 'Flotten är färdig. Nu måste gruppen välja om ni seglar nu eller väntar och försöker hitta fler överlevare innan avfärd.',
      buttonText: 'Till flottplatsen'
    }
  },
  raftBalance: {
    travelDays: 30,
    dailyFoodPerPerson: 1,
    dailyWaterPerPerson: 1,
    minPots: 30,
    totalIslandSurvivors: 33
  },
  conflictBalance: {
    baseChancePerTick: 0.002,
    chancePerRiskPoint: 0.00095,
    cooldownTicks: 6,
    moralePressureWeight: 0.45,
    personalLowMoraleWeight: 0.22,
    unmetNeedsWeight: 0.18,
    fatiguePressureWeight: 0.08,
    threatWeight: 0.07,
    foodSafetyPerPerson: 1.2,
    waterSafetyPerPerson: 1.2,
    foodProtection: 8,
    waterProtection: 8,
    shelterProtection: 12,
    fireProtectionPerLevel: 2.5,
    careProtectionPerFactor: 3,
    guardProtectionPerFactor: 1.5,
    mildRisk: 22,
    moderateRisk: 45,
    severeRisk: 72,
    breakdownMorale: 8,
    breakdownCooldownTicks: 12,
    awayTicks: 8
  },
  workBalance: {
    finalFactorClamp: { min: 0.35, max: 1.75 },
    skillFactorByLevel: {
      '-2': 0.55,
      '-1': 0.75,
      '0': 0.9,
      '1': 1.0,
      '2': 1.15,
      '3': 1.3,
      '4': 1.42,
      '5': 1.5
    },
    healthFactorBands: [
      { min: 90, factor: 1.05 },
      { min: 75, factor: 1.0 },
      { min: 50, factor: 0.9 },
      { min: 25, factor: 0.75 },
      { min: 0, factor: 0.55 }
    ],
    fatigueFactorBands: [
      { max: 24, factor: 1.05 },
      { max: 49, factor: 1.0 },
      { max: 69, factor: 0.9 },
      { max: 84, factor: 0.78 },
      { max: 100, factor: 0.6 }
    ],
    jobSkillMap: {
      wood: 'wood',
      food: 'food',
      water: 'water',
      make_tinder: 'craft',
      feed_fire: 'guard',
      clay: 'build',
      stone: 'build',
      bamboo: 'wood',
      timber: 'wood',
      fiber: 'craft',
      craft: 'craft',
      care: 'care',
      fish: 'fish',
      hunt: 'hunt',
      guard: 'guard',
      explore: 'explore'
    }
  },
  recipes: {
    stone_knife: { name: 'Gör stenkniv', timeHours: 1, costs: { stone: 1, fiber: 1 }, requirements: { discoveries: ['stone_knife'] }, yields: { stone_knives: 1 } },
    rope: { name: 'Tvinna rep', timeHours: 2, costs: { fiber: 2 }, requirements: { discoveries: ['rope'] }, yields: { rope: 1 } },
    net: { name: 'Gör nät', timeHours: 3, costs: { fiber: 3 }, requirements: { discoveries: ['net'] }, yields: { nets: 1 } },
    spear: { name: 'Gör spjut', timeHours: 2, costs: { logs: 1, stone: 1, fiber: 1 }, requirements: { discoveries: ['spear'] }, yields: { spears: 1 } },
    axe: { name: 'Gör yxa', timeHours: 4, costs: { logs: 1, stone: 2, rope: 1 }, requirements: { discoveries: ['axe'], capacityTools: { stone_knives: 1 } }, yields: { axes: 1 } },
    pots: { name: 'Bränn krukor', timeHours: 4, costs: { clay: 2 }, requiresFire: 1, requirements: { discoveries: ['pots'] }, yields: { pots: 1 } },
    hut: { name: 'Bygg hus', timeHours: 8, costs: { bamboo: 6, clay: 4 }, requirements: { discoveries: ['hut_building'], capacityTools: { stone_knives: 1 } }, yields: { huts: 1 } },
    backpack: { name: 'Gör ryggsäck', timeHours: 3, costs: { leather: 2 }, requirements: { discoveries: ['backpack'], capacityTools: { stone_knives: 1 } }, yields: { backpacks: 1 } },
    raft_log: { name: 'Bygg flotte: 1 stock', workspace: 'raft', timeHours: 4, costs: { timber: 1, rope: 2 }, yields: { raft_logs: 1 } },
    raft_sail: { name: 'Väv segel: 1 m²', workspace: 'raft', timeHours: 4, costs: { fiber: 5, leather: 2 }, yields: { raft_sail: 1 } },
    raft_rig: { name: 'Bygg rigg', workspace: 'raft', timeHours: 8, costs: { timber: 2, rope: 10 }, yields: { raft_rig: 1 } },
    raft_hut: { name: 'Bygg hytt', workspace: 'raft', timeHours: 12, costs: { bamboo: 20, clay: 30 }, yields: { raft_hut: 1 } }
  },
  jobs: {
    philosophize: { name: 'Filosoferar', icon: '&#128173;', mode: 'job', state: 'philosophize' },
    wood: { name: 'Samla ved', icon: '&#129717;', mode: 'job', state: 'work' },
    food: { name: 'Samla mat', icon: '&#129365;', mode: 'job', state: 'work' },
    water: { name: 'Samla vatten', icon: '&#128167;', mode: 'job', state: 'work' },
    fish: { name: 'Fiska', icon: '&#127907;', mode: 'job', state: 'work', requirements: { capacityTools: { nets: 1 } } },
    hunt: { name: 'Jaga', icon: '&#127993;', mode: 'job', state: 'work', requirements: { capacityTools: { spears: 1 } } },
    guard: { name: 'Vakta', icon: '&#128737;&#65039;', mode: 'job', state: 'work', requirements: { capacityTools: { spears: 1 } } },
    make_tinder: { name: 'Gör tändved', icon: '&#129718;', mode: 'job', state: 'work' },
    feed_fire: { name: 'Lägg på ved', icon: '&#128293;', mode: 'job', state: 'work' },
    clay: { name: 'Samla lera', icon: '&#129704;', mode: 'job', state: 'work', discovery: 'clay' },
    bamboo: { name: 'Samla bambu', icon: '&#127883;', mode: 'job', state: 'work', discovery: 'bamboo', requirements: { capacityTools: { stone_knives: 1 } } },
    timber: { name: 'Hugg timmer', icon: '&#129717;', mode: 'job', state: 'work', requirements: { capacityTools: { axes: 1 } } },
    stone: { name: 'Samla sten', icon: '&#129704;', mode: 'job', state: 'work', discovery: 'stone' },
    fiber: { name: 'Samla fibrer', icon: '&#129526;', mode: 'job', state: 'work' },
    rest: { name: 'Vila', icon: '&#128564;', mode: 'job', state: 'rest' },
    care: { name: 'Vårda', icon: '&#9877;&#65039;', mode: 'job', state: 'care' }
  }
};
